spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/insurance_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: senha123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: insurance_group
      auto-offset-reset: latest
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  logging:
    level:
      root: WARN
      org.springframework.web: ERROR
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus