spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurance_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: senha123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: insurance_group
      auto-offset-reset: earliest
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
